tap 'caskroom/cask'

brew 'git'
brew 'nvm'
brew 'openssh'
brew 'docker'
brew 'docker-compose'
brew 'docker-completion'
brew 'docker-compose-completion'

cask 'visual-studio-code'
cask 'google-chrome'
cask 'vlc'
cask 'hyper'
cask 'viscosity'
